### ISSUE TITLE
AttributeError: module 'PCONV' has no attribute 'RotateOp' in Rotate.py

### ISSUE THREAD

**Issue by yeonhw** [limuhit/VR-Video-Quality-in-the-Wild#3]
Hi, I encountered an issue while trying to use the `RotateOp` function in the `PCONV` module. The error message is as follows:
D:\Anaconda3\envs\dvqa\python.exe D:/Hugh/VR-Video-Quality-in-the-Wild/PCONV_operator/Rotate.py
Traceback (most recent call last):
  File "D:/Hugh/VR-Video-Quality-in-the-Wild/PCONV_operator/Rotate.py", line 51, in <module>
    vp = Rotate().to('cuda:0')
  File "D:/Hugh/VR-Video-Quality-in-the-Wild/PCONV_operator/Rotate.py", line 29, in __init__
    self.op = { gid : PCONV.RotateOp(interp, gid, time_it) for gid in self.device_list}
  File "D:/Hugh/VR-Video-Quality-in-the-Wild/PCONV_operator/Rotate.py", line 29, in <dictcomp>
    self.op = { gid : PCONV.RotateOp(interp, gid, time_it) for gid in self.device_list}
AttributeError: module 'PCONV' has no attribute 'RotateOp'

Is RotateOp defined elsewhere or has it been removed in the recent versions?
How can I resolve this issue or is there an alternative method to perform the same operation?
Please please help me！

**Comment by limuhit** [comment]
You may first install the extension using "python setup.py install".

**Comment by yeonhw** [comment]
Thank you for your response! I followed your suggestion and successfully solved the issue. I really appreciate your help！
